#!/usr/bin/env bash
#
# Run all installers and symlink dotfiles

set -e

cd "$(dirname "$0")/.."
cd "$(pwd -P)"

Echo "Bootstrapping"

Echo "Updating submodules"
git submodule init && git submodule update

script/platform
script/generic
script/symlinks
